# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import comms_pb2 as comms__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in comms_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceServiceStub(object):
    """Service definition for bidirectional communication between device and server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StatusStream = channel.stream_stream(
                '/com.opalcamera.test.DeviceService/StatusStream',
                request_serializer=comms__pb2.DeviceStatusResponse.SerializeToString,
                response_deserializer=comms__pb2.DeviceStatusRequest.FromString,
                _registered_method=True)
        self.EventStream = channel.stream_stream(
                '/com.opalcamera.test.DeviceService/EventStream',
                request_serializer=comms__pb2.DeviceEvent.SerializeToString,
                response_deserializer=comms__pb2.DeviceEventResponse.FromString,
                _registered_method=True)
        self.ServerAudioStream = channel.unary_stream(
                '/com.opalcamera.test.DeviceService/ServerAudioStream',
                request_serializer=comms__pb2.AudioStreamRequest.SerializeToString,
                response_deserializer=comms__pb2.AudioPacket.FromString,
                _registered_method=True)


class DeviceServiceServicer(object):
    """Service definition for bidirectional communication between device and server
    """

    def StatusStream(self, request_iterator, context):
        """The server send DeviceStatusRequests and expects responses in
        DeviceStatusResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EventStream(self, request_iterator, context):
        """The device streams DeviceEvents(s) and expects a DeviceEventResponse to ACK
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerAudioStream(self, request, context):
        """The device and server stream audio packets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StatusStream': grpc.stream_stream_rpc_method_handler(
                    servicer.StatusStream,
                    request_deserializer=comms__pb2.DeviceStatusResponse.FromString,
                    response_serializer=comms__pb2.DeviceStatusRequest.SerializeToString,
            ),
            'EventStream': grpc.stream_stream_rpc_method_handler(
                    servicer.EventStream,
                    request_deserializer=comms__pb2.DeviceEvent.FromString,
                    response_serializer=comms__pb2.DeviceEventResponse.SerializeToString,
            ),
            'ServerAudioStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerAudioStream,
                    request_deserializer=comms__pb2.AudioStreamRequest.FromString,
                    response_serializer=comms__pb2.AudioPacket.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.opalcamera.test.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.opalcamera.test.DeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceService(object):
    """Service definition for bidirectional communication between device and server
    """

    @staticmethod
    def StatusStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/com.opalcamera.test.DeviceService/StatusStream',
            comms__pb2.DeviceStatusResponse.SerializeToString,
            comms__pb2.DeviceStatusRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EventStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/com.opalcamera.test.DeviceService/EventStream',
            comms__pb2.DeviceEvent.SerializeToString,
            comms__pb2.DeviceEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerAudioStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.opalcamera.test.DeviceService/ServerAudioStream',
            comms__pb2.AudioStreamRequest.SerializeToString,
            comms__pb2.AudioPacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
